#!/usr/bin/env bash
# Installs and sets up HAProxy

apt-get update
apt-get install -y haproxy

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers
echo "
listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 126853-web-01 100.25.142.152
   server 126853-web-02 34.201.174.102
" >> /etc/haproxy/haproxy.cfg

systemctl start haproxy
